// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz2_biZGEoEKbM7bJ3jFRy4ZGShfRgHlM',
    appId: '1:373594840439:web:0d68806a6635e1d80b5572',
    messagingSenderId: '373594840439',
    projectId: 'learning-app-rafi',
    authDomain: 'learning-app-rafi.firebaseapp.com',
    storageBucket: 'learning-app-rafi.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6oFlgirF7ZH98_EHM9-4crAzphfiUgkw',
    appId: '1:373594840439:ios:c749f39a0ce980600b5572',
    messagingSenderId: '373594840439',
    projectId: 'learning-app-rafi',
    storageBucket: 'learning-app-rafi.firebasestorage.app',
    iosBundleId: 'com.example.languageLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz2_biZGEoEKbM7bJ3jFRy4ZGShfRgHlM',
    appId: '1:373594840439:web:135535677fb788650b5572',
    messagingSenderId: '373594840439',
    projectId: 'learning-app-rafi',
    authDomain: 'learning-app-rafi.firebaseapp.com',
    storageBucket: 'learning-app-rafi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6oFlgirF7ZH98_EHM9-4crAzphfiUgkw',
    appId: '1:373594840439:ios:c749f39a0ce980600b5572',
    messagingSenderId: '373594840439',
    projectId: 'learning-app-rafi',
    storageBucket: 'learning-app-rafi.firebasestorage.app',
    iosBundleId: 'com.example.languageLearningApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByDFFNZnuUxH2FCyo-JU6WIiC2F0LqyBE',
    appId: '1:373594840439:android:71b9312230ec89a60b5572',
    messagingSenderId: '373594840439',
    projectId: 'learning-app-rafi',
    storageBucket: 'learning-app-rafi.firebasestorage.app',
  );

}